name: adp-src-deeplse
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - joblib
  - pytorch
  - cpuonly
  - pytest
  - pip
  - pip:
      - -e .
